default_context:
    author_name: "Eva Maxfield Brown"
    author_email: "evamxb@uw.edu"
    hosting_github_username_or_org: "si2-urssi"
    project_name: "Software Search"
    project_slug: "eager"
    python_slug: "soft_search"
    project_short_description: "searching for software promises in grant applications"
    hosting_pypi_username: "evamaxfield"
    license: "MIT License"